[package]
name = "ignoreit"
description = "Quickly load .gitignore templates"
version = "2.1.0"
readme = "README.md"
repository = "https://github.com/jewlexx/ignoreit"
license = "MIT"
edition = "2021"
keywords = ["git", "ignore", "developer", "tools"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1.0.57"
spinners = "4.0.0"
directories = "4.0.1"
colored = "2.0.0"
lazy_static = "1.4.0"
git2 = "0.14.3"
pico-args = "0.4.2"

[build-dependencies]
cc = "1.0.73"
