[package]
name = "ignoreit"
description = "Quickly load .gitignore templates"
version = "1.1.0"
readme = "README.md"
repository = "https://github.com/jewlexx/ignoreit"
license = "MIT"
edition = "2021"
keywords = ["git", "ignore", "developer", "tools"]
categories = ["Command line utilities", "Development tools"]

[workspace]
members = ["cache", "remote", "macros"]

[dependencies]
anyhow = "1.0.56"
clap = { version = "3.1.8", features = ["derive"] }
colored = { version = "2.0.0", optional = true }

macros = { path = "./macros", version = "0.1.0" }
remote = { path = "./remote", version = "0.1.0" }
cache = { path = "./cache", optional = true, version = "0.1.0" }

[profile.release]
lto = true
opt-level = "s"
strip = true

[features]
default = ["cache"]
cache = ["dep:cache", "dep:colored"]
