[package]
name = "ignoreit"
description = "Quickly load .gitignore templates"
version = "2.4.0"
readme = "README.md"
repository = "https://github.com/jewlexx/ignoreit"
license = "MIT"
edition = "2021"
keywords = ["git", "ignore", "developer", "tools"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1.0.57"
spinners-rs = "2.3.0"
directories = "4.0.1"
colored = "2.0.0"
lazy_static = "1.4.0"
git2 = { version = "0.14.4", default-features = false, features = ["https", "vendored-libgit2", "vendored-openssl"] }
pico-args = "0.4.2"
dialoguer = "0.10.1"

[build-dependencies]
cc = "1.0.73"

[profile.release]
strip = true
lto = true
