[package]
name = "ignoreit"
description = "Quickly load .gitignore templates"
version = "2.4.9"
authors = ["Juliette Cordor"]
readme = "README.md"
repository = "https://github.com/jewlexx/ignoreit"
license = "MIT"
edition = "2021"
keywords = ["git", "ignore", "developer", "tools", "gitignore"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1.0.65"
directories = "4.0.1"
lazy_static = "1.4.0"
dialoguer = "0.10.2"
clap = { version = "4.0.29", features = ["derive"] }
mincolor = "2.0.1"
reqwest = { version = "0.11.12", features = ["json", "blocking"], default-features = false }
indicatif = { version = "0.17.1", features = ["rayon"] }
rayon = "1.5.3"
parking_lot = "0.12.1"

[profile.release]
strip = true
lto = true

[features]
default = ["native-tls"]
native-tls = ["reqwest/default-tls"]
vendored-tls = ["reqwest/native-tls-vendored"]
