[package]
name = "gitignore"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = { version = "1.0.78" }
reqwest = { version = "0.11.9", features = ["blocking", "json"] }
clap = { version = "3.1.6", features = ["derive"] } 
spinners = "3.1.0"
anyhow = "1.0.56"

[profile.release]
opt-level = "s"
strip = true
lto = true