[package]
name = "ignoreit"
description = "Quickly load .gitignore templates"
version = "2.4.2"
readme = "README.md"
repository = "https://github.com/jewlexx/ignoreit"
license = "MIT"
edition = "2021"
keywords = ["git", "ignore", "developer", "tools"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1.0"
spinners-rs = "2.3"
directories = "4.0"
colored = "2.0"
lazy_static = "1.4"
git2 = { version = "0.14", default-features = false, features = ["https"] }
dialoguer = "0.10"
clap = { version = "3.1", features = ["derive"] }


[profile.release]
strip = true
lto = true

[features]
default = []
vendored-libgit2 = ["git2/vendored-libgit2"]
vendored-openssl = ["git2/vendored-openssl"]
