[package]
name = "ignoreit"
description = "Quickly load .gitignore templates"
version = "1.0.0"
readme = "README.md"
repository = "https://github.com/jewlexx/ignoreit"
license = "MIT"
edition = "2021"
keywords = ["git", "ignore", "developer", "tools"]
categories = ["Command line  utilities", "Development tools"]

[workspace]
members = ["cache", "remote", "macros"]

[dependencies]
anyhow = "1.0.56"
colored = "2.0.0"
clap = { version = "3.1.8", features = ["derive"] }
reqwest = { version = "0.11.10", features = ["blocking","json"] }

macros = { path = "./macros" }
cache = { path = "./cache", optional = true }
remote = { path = "./remote"}

[profile.release]
lto = true
opt-level = "s"
strip = true

[features]
default = ["cache"]
cache = ["dep:cache"]
