[package]
name = "gitignore"
version = "1.0.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
clap = { version = "3.1.6", features = ["derive"] } 
serde_json = "1.0.79"
spinners = "3.1.0"
anyhow = "1.0.56"

[profile.release]
opt-level = "s"
strip = true
lto = true