[package]
name = "ignoreit"
version = "1.0.0"
edition = "2021"
description = "Quickly download .gitignore templates for nearly any project"
license = "MIT"
repository = "https://github.com/jewlexx/ignoreit"
readme = "README.md"
keywords = ["git", "ignore"]
categories = ["command-line-utilities"]

[dependencies]
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
clap = { version = "3.1.6", features = ["derive"] }
pico-args = "0.4.2"
serde_json = "1.0.79"
spinners = "3.1.0"
anyhow = "1.0.56"

[profile.release]
opt-level = "s"
strip = true
lto = true