[package]
name = "ignoreit"
description = "Quickly load .gitignore templates"
version = "1.0.0"
readme = "README.md"
repository = "https://github.com/jewlexx/ignoreit"
license = "MIT"
edition = "2021"
keywords = ["git", "ignore", "developer", "tools"]
categories = ["Command line  utilities", "Development tools"]

[workspace]
members = ["cache", "remote", "macros"]

[dependencies]
anyhow = "1.0.56"
serde_json = "1.0.79"
spinners = "3.1.0"
colored = "2.0.0"

[dependencies.clap]
features = ["derive"]
version = "3.1.8"

[dependencies.reqwest]
features = ["blocking", "json"]
version = "0.11.10"

[dependencies.macros]
path = "./macros"

[dependencies.cache]
path = "./cache"
optional = true

[dependencies.remote]
path = "./remote"

[profile.release]
lto = true
opt-level = "s"
strip = true

[features]
default = ["cache"]
cache = ["dep:cache"]
