[package]
name = "ignoreit"
description = "Quickly load .gitignore templates"
version = "2.4.3"
readme = "README.md"
repository = "https://github.com/jewlexx/ignoreit"
license = "MIT"
edition = "2021"
keywords = ["git", "ignore", "developer", "tools"]
categories = ["command-line-utilities", "development-tools"]

[dependencies]
anyhow = "1.0.60"
spinners-rs = "2.3.0"
directories = "4.0.1"
lazy_static = "1.4.0"
git2 = { version = "0.15.0", default-features = false, features = ["https"] }
dialoguer = "0.10.2"
clap = { version = "3.2.16", features = ["derive"] }
mincolor = "2.0.1"
serde = { version = "1.0.141", features = ["derive"] }
serde_json = "1.0.82"
thiserror = "1.0.31"
reqwest = { version = "0.11.11", features = ["json", "blocking"] }
indicatif = { version = "0.17.0", features = ["rayon"] }
rayon = "1.5.3"


[profile.release]
strip = true
lto = true

[features]
default = []
vendored = ["vendored-libgit2", "vendored-openssl"]
vendored-libgit2 = ["git2/vendored-libgit2"]
vendored-openssl = ["git2/vendored-openssl"]
