[package]
name = "ignoreit"
description = "Quickly load .gitignore templates"
version = "1.0.0"
readme = "README.md"
repository = "https://github.com/jewlexx/ignoreit"
license = "MIT"
edition = "2021"
keywords = ["git", "ignore", "developer", "tools"]
categories = ["Command line  utilities", "Development tools"]

[dependencies]
anyhow = "1.0.56"
directories = "4.0.1"
git2 = "0.14.2"
lazy_static = "1.4.0"
serde_json = "1.0.79"
spinners = "3.1.0"
colored = "2.0.0"

[dependencies.clap]
features = ["derive"]
version = "3.1.8"

[dependencies.reqwest]
features = ["blocking", "json"]
version = "0.11.10"

[profile.release]
lto = true
opt-level = "s"
strip = true
